### ISSUE TITLE
Call to undefined method Rancherize\Commands\PushCommand::getInServiceChecker()

### ISSUE THREAD

**Issue by justb81** [ipunkt/rancherize#62]
```
Fatal error: Uncaught Error: Call to undefined method Rancherize\Commands\PushCommand::getInServiceChecker() in /opt/rancherize/app/Commands/PushCommand.php:117
Stack trace:
#0 /opt/rancherize/vendor/symfony/console/Command/Command.php(264): Rancherize\Commands\PushCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /opt/rancherize/vendor/symfony/console/Application.php(906): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /opt/rancherize/vendor/symfony/console/Application.php(224): Symfony\Component\Console\Application->doRunCommand(Object(Rancherize\Commands\PushCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /opt/rancherize/vendor/symfony/console/Application.php(125): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Objec in /opt/rancherize/app/Commands/PushCommand.php on line 117
```

Run over docker, with ecr and using the gitlab-build branch (merged from current master)

**Comment by justb81** [comment]
```
Fatal error: Uncaught Error: Call to undefined method Rancherize\Commands\PushCommand::inServiceChecker() in /opt/rancherize/app/Commands/PushCommand.php:117
Stack trace:
#0 /opt/rancherize/vendor/symfony/console/Command/Command.php(264): Rancherize\Commands\PushCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 /opt/rancherize/vendor/symfony/console/Application.php(906): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /opt/rancherize/vendor/symfony/console/Application.php(224): Symfony\Component\Console\Application->doRunCommand(Object(Rancherize\Commands\PushCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /opt/rancherize/vendor/symfony/console/Application.php(125): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(S in /opt/rancherize/app/Commands/PushCommand.php on line 117
```
